In [1]:
import numpy as np
import pandas as pd
import matplotlib as mlt

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_5d560e5c353948d3add9e74d8feeb31e = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='pbsVPWOMCfTbBhUJclkH6jfqY6U4eQ5B-Tubr4by-qBp',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_5d560e5c353948d3add9e74d8feeb31e.get_object(Bucket='sai1-donotdelete-pr-fmz7l0bzc3kyxt',Key='Black Friday Sales Prediction.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



Gender  Age  Occupation  Stay in Years  Marital Status  Prod_category  \
0      F   10          10              2               0              3   
1      F   10          10              2               0              1   
2      F   10          10              2               0             12   
3      F   10          10              2               0             12   
4      M   60          16              5               0              8   

   Category  Purchase  
0         1      8370  
1         1     15200  
2         1      1422  
3         1      1057  
4         0      7969

In [3]:
dataset

Gender  Age  Occupation  Stay in Years  Marital Status  Prod_category  \
0           F   10          10              2               0              3   
1           F   10          10              2               0              1   
2           F   10          10              2               0             12   
3           F   10          10              2               0             12   
4           M   60          16              5               0              8   
5           M   30          15              3               0              1   
6           M   48           7              2               1              1   
7           M   48           7              2               1              1   
8           M   48           7              2               1              1   
9           M   30          20              1               1              8   
10          M   30          20              1               1              5   
11          M   30          20              1               1              8   
12          M   30          20              1               1              8   
13          M   30          20              1               1              1   
14          F   53           9              1               0              5   
15          F   53           9              1               0              4   
16          F   53           9              1               0              2   
17          F   53           9              1               0              5   
18          M   40           1              1               1              1   
19          M   30          12              5               1              1   
20          M   30          12              5               1              5   
21          M   30          12              5               1              8   
22          M   30          12              5               1              8   
23          M   30          12              5               1              8   
24          M   30          12              5               1              1   
25          M   30          17              0               0              6   
26          M   30          17              0               0              8   
27          M   30          17              0               0              5   
28          M   30          17              0               0              5   
29          F   40           1              5               1              2   
...       ...  ...         ...            ...             ...            ...   
537547      M   22          18              1               0              1   
537548      M   53           1              1               1             15   
537549      M   53           1              1               1              2   
537550      M   48           3              3               0              1   
537551      M   48           3              3               0              5   
537552      M   48           3              3               0              6   
537553      M   48           3              3               0             10   
537554      M   48           3              3               0              5   
537555      M   48           3              3               0             13   
537556      M   22          20              1               1              8   
537557      M   22          20              1               1              2   
537558      M   22          20              1               1              8   
537559      M   22          20              1               1              8   
537560      M   22          20              1               1              8   
537561      M   22          20              1               1              8   
537562      M   22          20              1               1              1   
537563      M   22          20              1               1              8   
537564      M   22          20              1               1              5   
537565 

In [4]:
x=dataset.iloc[:,:7].values
x

array([['F', 10, 10, ..., 0, 3, 1],
       ['F', 10, 10, ..., 0, 1, 1],
       ['F', 10, 10, ..., 0, 12, 1],
       ..., 
       ['M', 40, 16, ..., 0, 8, 0],
       ['M', 40, 16, ..., 0, 5, 0],
       ['M', 40, 16, ..., 0, 5, 0]], dtype=object)

In [5]:
y=dataset.iloc[:,7:8].values
y

array([[ 8370],
       [15200],
       [ 1422],
       ..., 
       [ 8043],
       [ 7172],
       [ 6875]])

In [6]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [7]:
x[:,0]=lb.fit_transform(x[:,0])
x

array([[0, 10, 10, ..., 0, 3, 1],
       [0, 10, 10, ..., 0, 1, 1],
       [0, 10, 10, ..., 0, 12, 1],
       ..., 
       [1, 40, 16, ..., 0, 8, 0],
       [1, 40, 16, ..., 0, 5, 0],
       [1, 40, 16, ..., 0, 5, 0]], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split                
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)
y_predict = regressor.predict([[1,30,17,1,0,1,0]])
y_predict

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


array([ 15002.81243865])

In [10]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2019-06-20 05:50:16,322 - watson_machine_learning_client.metanames - WARNING - 'AUTHOR_EMAIL' meta prop is deprecated. It will be ignored.


In [11]:
wml_credentials={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "access_key":"qhdZC-DaUmuRnel1kxLHgaHMUNnB_6nlBSpQZ6N3w0Ce",
    "username":"4304486f-8902-4614-80fe-bc2b70088dc2",
    "password":"4549c902-bd45-44e2-9981-ac08d4266e19",
    "instance_id": "900c0ffa-6d8a-4319-8866-b333271e62c6"
}

In [12]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [13]:
model_props={client.repository.ModelMetaNames.AUTHOR_NAME:"IBM",
             client.repository.ModelMetaNames.AUTHOR_EMAIL:"ibm@ibm.com",
             client.repository.ModelMetaNames.NAME:"Random Forest"
            }

In [15]:
model_artifact=client.repository.store_model(regressor,meta_props=model_props)

In [16]:
published_model_uid=client.repository.get_model_uid(model_artifact)

In [17]:
created_deployment=client.deployments.create(published_model_uid,name="Random Forest")



#######################################################################################

Synchronous deployment creation for uid: '83ef331f-70c2-4e01-82f2-2b20341e8b18' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='611007ac-59cc-4ca0-a87d-ce27f0229df5'
------------------------------------------------------------------------------------------------




In [18]:
scoring_endpoint=client.deployments.get_scoring_url(created_deployment)
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/900c0ffa-6d8a-4319-8866-b333271e62c6/deployments/611007ac-59cc-4ca0-a87d-ce27f0229df5/online'